/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="high-contrast"]'],
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-primary": "var(--color-brand-primary)",
        "navy": "var(--color-navy)",
        "navy-mid": "var(--color-navy-mid)",
        "teal": "var(--color-teal)",
        "teal-dim": "var(--color-teal-dim)",
        "slate": "var(--color-slate)",
        "slate-light": "var(--color-slate-light)",
        "white": "var(--color-white)",
        "brand-primaryHover": "var(--color-brand-primaryHover)",
        "brand-secondary": "var(--color-brand-secondary)",
        "brand-secondaryHover": "var(--color-brand-secondaryHover)",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-surface": "var(--color-inverse-surface)",
        "error-container": "var(--color-error-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary": "var(--color-primary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary": "var(--color-on-tertiary)",
        "secondary-container": "var(--color-secondary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary": "var(--color-secondary)",
        "on-background": "var(--color-on-background)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error": "var(--color-on-error)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "background": "var(--color-background)",
        "on-primary": "var(--color-on-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "outline": "var(--color-outline)",
        "surface": "var(--color-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "surface-container": "var(--color-surface-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "error": "var(--color-error)",
        "on-secondary": "var(--color-on-secondary)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "outline-variant": "var(--color-outline-variant)",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "section-padding-v-mobile": "64px",
        "gutter": "24px",
        "section-padding-v": "120px",
        "container-max": "1280px",
        "stack-gap": "16px",
        "group-gap": "40px"
      },
      fontFamily: {
        "sans": ["DM Sans", "sans-serif"],
        "display": ["Syne", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em" }],
        "display-lg-mobile": ["2.75rem", { lineHeight: "3.25rem", letterSpacing: "-0.02em" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem" }],
        "label-caps": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.05em" }],
      },
      fontWeight: {
        "display-lg": "800",
        "display-lg-mobile": "800",
        "headline-md": "700",
        "headline-sm": "700",
        "body-lg": "400",
        "body-md": "400",
        "label-caps": "600",
      }
    },
  },
  plugins: [],
}
